# Generated by Django 5.2.7 on 2025-10-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0003_collectionassignment_collection_cycle_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='HKSWardAssignment',
            fields=[
                ('ward_id', models.CharField(help_text='e.g., HKS-W05', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('worker1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ward_assignments', to='workers.workerprofile')),
                ('worker2', models.ForeignKey(blank=True, help_text='Optional second worker for the ward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_ward_assignments', to='workers.workerprofile')),
            ],
        ),
    ]
