# Generated by Django 5.2.7 on 2025-10-06 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(help_text='The waste collection ward assigned by the Admin.', max_length=10)),
                ('household_id', models.CharField(help_text='Unique identifier for the household (e.g., Door No.)', max_length=50, unique=True)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resident Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResidentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('MISSED', 'Missed Collection'), ('BEHAVIOR', 'Rude Behaviour'), ('DELAY', 'Collection Delay'), ('OTHER', 'Other Issue')], max_length=50)),
                ('details', models.TextField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='complaint_proofs/')),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.residentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid_online', models.BooleanField(default=True, help_text='True for digital payment, False for cash.')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('worker_who_received_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerprofile')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.residentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BinFullAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_proof', models.ImageField(upload_to='alert_proofs/')),
                ('location_detail', models.CharField(default='Household Bin', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('ASSIGNED', 'Worker Assigned'), ('CLEARED', 'Bin Cleared')], default='PENDING', max_length=20)),
                ('worker_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerprofile')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.residentprofile')),
            ],
        ),
    ]
