# Generated by Django 5.2.7 on 2025-10-06 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=6)),
                ('billed_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.residentprofile')),
            ],
            options={
                'unique_together': {('resident', 'billed_date')},
            },
        ),
    ]
