# Generated by Django 5.2.7 on 2025-10-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_billingdue'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(help_text='Transaction ID or Manual Receipt Number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='worker_who_received_cash',
            field=models.ForeignKey(blank=True, help_text='Worker who confirmed receipt of cash payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workerprofile'),
        ),
    ]
