# Generated by Django 5.2.7 on 2025-10-17 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_payment_receipt_photo_alter_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_month', models.IntegerField()),
                ('collection_year', models.IntegerField()),
                ('reason', models.CharField(choices=[('VACATION', 'Away/Vacation'), ('LOW', 'Low Waste Volume'), ('OTHER', 'Other')], default='LOW', max_length=100)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.residentprofile')),
            ],
            options={
                'unique_together': {('resident', 'collection_month', 'collection_year')},
            },
        ),
    ]
