# Generated by Django 5.2.7 on 2025-10-06 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=50, unique=True)),
                ('assigned_wards', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Worker Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='worker_complaint_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(default=django.utils.timezone.now)),
                ('household_id', models.CharField(max_length=50)),
                ('is_collected', models.BooleanField(default=False)),
                ('collection_time', models.DateTimeField(blank=True, null=True)),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='collection_proofs/')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerprofile')),
            ],
            options={
                'unique_together': {('assignment_date', 'household_id')},
            },
        ),
    ]
