# Generated by Django 5.2.7 on 2025-10-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercomplaint',
            name='issue_type',
            field=models.CharField(choices=[('VEHICLE', 'Vehicle/Truck Breakdown'), ('ACCESS', 'Access/Lockout Issue'), ('SAFETY', 'Safety/Hazardous Waste'), ('ROUTE', 'Route/Mapping Problem'), ('OTHER', 'Other Field Issue')], max_length=50),
        ),
    ]
