# Generated by Django 5.2.7 on 2025-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workercomplaint_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionassignment',
            name='collection_cycle_day',
            field=models.IntegerField(default=1, help_text="Day of the month's collection cycle (1-10)."),
        ),
    ]
