# Generated by Django 5.2.7 on 2025-10-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_collectionassignment_collection_cycle_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(max_length=50, unique=True)),
                ('lsgi_area', models.CharField(default='LSGI Central', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supervisor Profiles',
            },
        ),
        migrations.CreateModel(
            name='HKSWardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.CharField(help_text='The unique geographic ID of the Ward (e.g., LSGI-W05)', max_length=50, unique=True)),
                ('service_points_count', models.IntegerField(default=500, help_text='Number of households/service points in the ward.')),
                ('worker1', models.ForeignKey(help_text='Primary HKS member assigned to this ward.', on_delete=django.db.models.deletion.RESTRICT, related_name='primary_wards', to='workers.workerprofile')),
                ('worker2', models.ForeignKey(blank=True, help_text='Secondary HKS member assigned to this ward.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='secondary_wards', to='workers.workerprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.supervisorprofile')),
            ],
            options={
                'verbose_name_plural': 'HKS Ward Assignments',
            },
        ),
    ]
